export default [
  "#zurna kanalı",
  "0.5 tombow kalem ucu",
  "6 haneli icq numarası",
  "a drinking song",
  "ajdar anık",
  "akdeniz foku",
  "akmar müdavimi",
  "alain sutter",
  "anders frisk",
  "art direktör",
  "art vandaley",
  "arzuhalci",
  "atlıkarınca",
  "avrupa birliği üye ülke vatandaşı",
  "babazula",
  "bahtsız bedevi",
  "batık banka mudii",
  "bağkur emeklisi",
  "bean burger",
  "berber fil",
  "beyaz çorap giyen",
  "birden fazla doğumgünü hediyesi",
  "birinci nesil hayvan",
  "blythe doll",
  "bob kelso",
  "bot",
  "boğa burcu",
  "california valisi",
  "ceren",
  "chai chen",
  "ciriaco sforza",
  "claire bennett",
  "clarence seedorf",
  "comanchero",
  "cosmo kramer",
  "çeribaşı",
  "dan shea",
  "daniel amokachi",
  "daniele massaro",
  "darkwing duck",
  "david hewlett",
  "dewey",
  "donut",
  "duman avcısı",
  "dön bebeğim",
  "emmanuel amunike",
  "emmoğlu",
  "eski sevgili",
  "falçatalı travesti",
  "fazla bileti olan var mı? diye soran insan",
  "florin raducioiu",
  "george costanza",
  "george oscar bluth",
  "gibi gibi",
  "gisele bündchen",
  "gondor vekilharcı",
  "greenpeace üyesi",
  "hakan mild",
  "halısaha kalecisi",
  "hayalet avcısı",
  "hayırsız evlat",
  "haza beyefendi",
  "haza hanımefendi",
  "haçlı ordusu",
  "headbanger",
  "hiro nakamura",
  "hobbit",
  "ikiden fazla uyku düzeni",
  "intellimouse",
  "ipod",
  "isviçreli futbolcu",
  "john locke",
  "jorge campos",
  "josé emilio amavisca",
  "julian sark",
  "kanun hükmünde kararname",
  "kardak sakini",
  "kardanadam",
  "karıncayiyen",
  "katee sackhoff",
  "kayserili işadamı",
  "kim bauer",
  "klingon gemisi komutanı",
  "kombine biletli taraftar",
  "krassimir balakov",
  "kristel kama",
  "kurbanlık koyun",
  "laptop pili",
  "laudrup kardeşler",
  "lauren graham",
  "lolipop",
  "malcolm",
  "marissa cooper",
  "marlboro paketi",
  "mary-louise parker",
  "melanie pain",
  "mia kirshner",
  "millennium fuck",
  "mr.eko",
  "mr.robot",
  "muz kabuğu",
  "nokia şarjı",
  "nutella kavanozu",
  "oregon valisi",
  "ornitorenk",
  "ortam çocuğu",
  "oğlak burcu",
  "paratrooper",
  "petek dinçöz",
  "photoshop layer'ı",
  "pili biten vibratör",
  "piyes",
  "plastik ördek",
  "punk",
  "rafael van der vaart",
  "rashidi yekini",
  "ray romano",
  "real doll",
  "reese",
  "retina",
  "ron rifkin",
  "rus turist",
  "sean dundee",
  "squidward tentacles",
  "stephane chapuisat",
  "taklit ülker ürünü",
  "tatil kasabası bilekliği",
  "tiki",
  "tobias fünke",
  "tony almeida",
  "trifon ivanov",
  "turuncu kulaklıklı walkman",
  "uche okechukwu",
  "ulf kirsten",
  "veresiyeci",
  "victor garber",
  "viktor onopko",
  "vize görevlisi",
  "wii",
  "will tippin",
  "yunan başkonsolosu",
  "yuri nikiforov",
  "zekeriya beyaz",
];
