const sentences: string[] = [
  "zurna kanalı",
  "0.5 tombow kalem ucu",
  "6 haneli icq numarası",
  "a drinking song",
  "ajdar anık",
  "akdeniz foku",
  "akmar müdavimi",
  "akşam yemeği",
  "art director",
  "art vandelay",
  "arzuhalci",
  "atlıkarınca",
  "avrupa birliği üye ülke vatandaşı",
  "ayakkabı kutusu",
  "babazula",
  "bahtsız bedevi",
  "tim burton",
  "baba parası",
  "batık banka mudii",
  "bağkur emeklisi",
  "bean burger",
  "berber fil",
  "berlin duvarı",
  "beyaz çorap giyen",
  "birden fazla doğum günü hediyesi",
  "dinozor",
  "blythe doll",
  "bob kelso",
  "bob marley",
  "terazi burcu kadını",
  "caretta caretta",
  "california valisi",
  "liseli ceren",
  "chai chen",
  "claire bennet",
  "clark kent",
  "comanchero",
  "saksafon teli",
  "cosmo kramer",
  "çeribaşı",
  "darkwing duck",
  "dewey",
  "donut",
  "duman avcısı",
  "dön bebeğim",
  "emmanuelle 2000",
  "emmoğlu",
  "eski sevgili",
  "falçatalı travesti",
  "fazla bileti olan var mı? diye soran insan",
  "george costanza",
  "george oscar bluth",
  "gibi gibi",
  "gizli ajanda",
  "gondor vekilharcı",
  "greenpeace üyesi",
  "halısaha kalecisi",
  "hayalet avcısı",
  "hayırsız evlat",
  "haza beyefendi",
  "haza hanımefendi",
  "haçlı ordusu",
  "headbanger",
  "kelebek",
  "hiro nakamura",
  "hobbit",
  "ikiden fazla uyku düzeni",
  "intellimouse",
  "ipod",
  "isviçreli futbolcu",
  "john locke",
  "julian sark",
  "kanun hükmünde kararname",
  "papatya",
  "kardak sakini",
  "kardanadam",
  "karıncayiyen",
  "katee sackhoff",
  "kayserili işadamı",
  "kim bauer",
  "klingon gemisi komutanı",
  "kombine biletli taraftar",
  "kristel kama",
  "kurbanlık koyun",
  "laptop pili",
  "liv tyler",
  "lolipop",
  "malcolm",
  "marissa cooper",
  "marlboro paketi",
  "mary-louise parker",
  "melanie pain",
  "mia kirshner",
  "millennium fuck",
  "milli piyango bileti",
  "mr.eko",
  "mr.robot",
  "muz kabuğu",
  "nokia şarjı",
  "nutella kavanozu",
  "oregon valisi",
  "ornitorenk",
  "ortam çocuğu",
  "ikizler burcu erkeği",
  "patric star",
  "paratrooper",
  "peçeteye yazılmış telefon numarası",
  "petek dinçöz",
  "photoshop layer'ı",
  "pili biten vibratör",
  "piyes",
  "plastik ördek",
  "plüton",
  "polaroid fotoğraf",
  "punk",
  "ray romano",
  "real doll",
  "retina",
  "ron rifkin",
  "rus turist",
  "sean penn",
  "spongebob squarepants",
  "squidward tentacles",
  "taklit ülker ürünü",
  "tatil kasabası bilekliği",
  "tiki",
  "tony stark",
  "toptan gıda satıcısı",
  "tüketici hakları derneği üyesi",
  "turuncu kulaklıklı walkman",
  "tüylü oyuncak",
  "unicorn",
  "veresiyeci",
  "victor garber",
  "vize görevlisi",
  "wii",
  "will tippin",
  "william shatner",
  "yunan başkonsolosu",
  "zekeriya beyaz",
];

const randomSentence = (): string => {
  const sentence =
    sentences[Math.round((sentences.length - 1) * Math.random())];
  return sentence;
};

export default randomSentence;
